
Application:
  serviceType: ingress
  ingressHost: "librenms.example.com"

credentials:
  application:
    administrativeUser: "admin"
    administrativePassword: "adminPassword"
    administrativeEmail: "admin@example.org"
  mysql:
    rootPassword: "mysqlRootPassword"
    user: "librenms"
    password: "userPassword"
  ldap:
    bindUser: "ldapBindUser"
    bindDN:
    bindPassword: "ldapBindPassword"
  active_directory:
    bindUser: "adBindUser"
    bindDN:
    bindPassword: "adBindPassword"
  redis:
    password: "redisPassword"

