
image:
  repositoryRoot: "docker.io/tpboudreau/librenms-device"
  tag: "0.1.8"

Devices:
- DeviceName: "test-device-zero"
  SNMPVersion: "v2c"
- DeviceName: "test-device-one"
  SNMPVersion: "v2c"
- DeviceName: "test-device-two"
  SNMPVersion: "v2c"
- DeviceName: "test-device-three"
  SNMPVersion: "v2c"
- DeviceName: "test-device-alpha"
  SNMPVersion: "v3"
- DeviceName: "test-device-beta"
  SNMPVersion: "v3"
- DeviceName: "test-device-gamma"
  SNMPVersion: "v3"
- DeviceName: "test-device-delta"
  SNMPVersion: "v3"

